image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - test
  - publish

branch::test:
  stage: test
  except:
    - tags
  script: |
    dotnet test -v minimal -c Release /p:CollectCoverage=true

branch::publish:
  stage: publish
  only:
    - tags
  script: |
    echo ---------------------------------------------- TESTING

    dotnet test -v minimal -c Release /p:CollectCoverage=true

    echo ---------------------------------------------- VERSIONING

    echo VERSION := $CI_COMMIT_TAG
    
    sed -i -- "s/1\.0\.0\.0/${CI_COMMIT_TAG}/g" ./BehavioralLink/BehavioralLink.csproj
    
    echo ---------------------------------------------- BUILDING

    cd BehavioralLink
    dotnet pack -c Release
    cd ..
    
    echo ---------------------------------------------- PUBLISHING

    cd ./BehavioralLink/bin/Release
    NUGET_PKG=$(ls *.nupkg)
    echo PACKAGE := $NUGET_PKG
    dotnet nuget push $NUGET_PKG -k $NUGET_KEY -s https://api.nuget.org/v3/index.json
    cd ../../..
    